### PR TITLE
feat: create high-level MVs and backing tables (FC-0024)

### PR DESCRIPTION
**Pull request by SoryRawyer**
PR for [issue #58 ](https://github.com/openedx/tutor-contrib-oars/issues/58)

Creates tables for:
- video playback events
- problem interaction events
- navigation events

The `problem_events` table omits the browser's `problem_check` event from the `problem_events` table. There is a note in the code, but this was primarily because from what I can tell there's nothing in the browser events that isn't in the server events. During my testing, I only came across one instance where browser events where sent without an accompanying server event, and that was when there was a server error (something about my development environment must not be fully set up properly). As a corollary to this, we save a considerable amount of space by only keeping the server events.

I'd love some feedback on the naming conventions, included attributes, and data types, in addition to anything else that might cross your mind.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey @SoryRawyer, thank you for this contribution! Please let us know when it is ready for review.

**Comment by bmtcril** [comment]
Hey @SoryRawyer lgtm, just needs the commit message on the 2nd commit updated

**Comment by SoryRawyer** [comment]
Thanks! This will be the last commit message reminder, I promise.

**Comment by Ian2012** [comment]
@bmtcril For another PR, if the schema definition file is above 500 lines, we should separate it into different .sql files

**Comment by bmtcril** [comment]
@Ian2012 We should probably make a call on whether we're going to use the Alembic migrations. If so we can just move it all to those, but I haven't had time to look into the specifics of implementing it yet. I created this ticket to try them out, I don't think it will be a lot of work, or at least hope not. https://github.com/openedx/tutor-contrib-oars/issues/68

**Review by bmtcril — APPROVED** [review]

**Pull request merged**
